sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          packages:
            - libxdg-basedir-dev
            - libflac++-dev
            - libmad0-dev
            - libpulse-dev
            - libopenal-dev
            - libasound2-dev
      env:
        - COMPILER=3.7 LLVM_VERSION=3.7.1 BUILD_TYPE=Debug
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxdg-basedir-dev
            - libflac++-dev
            - libmad0-dev
            - libpulse-dev
            - libopenal-dev
            - libasound2-dev
      env:
        - COMPILER=3.7 LLVM_VERSION=3.7.1 BUILD_TYPE=Release
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxdg-basedir-dev
            - libflac++-dev
            - libmad0-dev
            - libpulse-dev
            - libopenal-dev
            - libasound2-dev
      env:
        - COMPILER=3.8 LLVM_VERSION=3.8.0 BUILD_TYPE=Debug
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxdg-basedir-dev
            - libflac++-dev
            - libmad0-dev
            - libpulse-dev
            - libopenal-dev
            - libasound2-dev
      env:
        - COMPILER=3.8 LLVM_VERSION=3.8.0 BUILD_TYPE=Release
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libxdg-basedir-dev
            - libflac++-dev
            - libmad0-dev
            - libpulse-dev
            - libopenal-dev
            - libasound2-dev
      env:
        - COMPILER=5 BUILD_TYPE=Debug
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libxdg-basedir-dev
            - libflac++-dev
            - libmad0-dev
            - libpulse-dev
            - libopenal-dev
            - libasound2-dev
      env:
        - COMPILER=5 BUILD_TYPE=Release
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libxdg-basedir-dev
            - libflac++-dev
            - libmad0-dev
            - libpulse-dev
            - libopenal-dev
            - libasound2-dev
      env:
        - COMPILER=6 BUILD_TYPE=Debug
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libxdg-basedir-dev
            - libflac++-dev
            - libmad0-dev
            - libpulse-dev
            - libopenal-dev
            - libasound2-dev
      env:
        - COMPILER=6 BUILD_TYPE=Release
    - compiler: clang
      os: osx
      env:
        - BUILD_TYPE=Debug
      osx_image: xcode7.3
    - compiler: clang
      os: osx
      env:
        - BUILD_TYPE=Release
      osx_image: xcode7.3

before_install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR}/local
  - cd ${DEPS_DIR}
  - export CXXFLAGS="-isystem ${DEPS_DIR}/local/include"
  - export PKG_CONFIG_PATH=${DEPS_DIR}/local/lib/pkgconfig
  - export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${DEPS_DIR}/local/lib"
  - export LDFLAGS="-L${DEPS_DIR}/local/lib"

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi
    
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install libtag openal libmad flac
    fi

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      tar xf taglib-1.11.tar.gz
      cd taglib-1.11
      cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX:PATH=${DEPS_DIR}/local .
      make -j4 install
      cd ..
      wget http://www.ffmpeg.org/releases/ffmpeg-3.1.1.tar.bz2
      tar xf ffmpeg-3.1.1.tar.bz2
      cd ffmpeg-3.1.1 && ./configure --prefix=${DEPS_DIR}/local --disable-shared --disable-avdevice --disable-doc --disable-htmlpages --disable-manpages --disable-programs --disable-encoders --disable-muxers --disable-decoders --disable-swscale --disable-yasm --disable-everything && make -j4 install
      cd ..
    fi
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - git clone -b develop --single-branch --recursive https://github.com/dirkvdb/utils.git ../utils

script:
  - git submodule update --init --recursive
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DSTANDALONE=ON .
  - make -j4
  - CTEST_OUTPUT_ON_FAILURE=1 make test

after_failure:
  - cat Testing/Temporary/LastTest.log
